sudo: false

language: python

cache: pip

python:
    - 3.6
    - 3.7

deploy:
  provider: pypi
    user: Mdslino
    password:
      secure: oib/HHCKVC0rzR7vXagIYHYsIHQW7KvY8HvZvaosS1rhWz1xHKf0/SwZotdJbobDJ+CIL9acPQweJ1CvQ9mQ26qRe3TyloBHK3onnPWgFTKPweCoZXY5H36dokaTFRrL7rVOi2pRL5UCiYF2EDVG/xHxGnEvQE77UTl5KTAtdJcczUFqyFzNFjtAmK+7J0/opbtAGrVNmi61MOfBi/jffPtAL0WZlOf5YvFZYfvzhliM0tP3H8iBlUFEzUzT2w2A7L7+G/PW5VFy7eua6DPpzxyYotXdix3U4iwSgnAkaBLvU4mMDbAzxGA1zYGVy4Z+RHU6cCZQhdPV7GaiQyLk5uffAAaRaXXm3uPY2aGmg5NK8vHtVTdlzfGMw041SDl36Ukeru1Yjx2DtpMdyBT63hLt9JZZVHwBz9U6/wm6m/dCITFLvN3mOBDQNqp3tluafcVS8MN2GMEWg+5leaT/AQFq67AxdrCrB3+xXWldMBM284D4p9TMxIPJQucFKqMB3wJ/JnyQr4spwHTwXHwVGXlBb3hUQqznAKuLjpJjh6gLpTs324G+nKoNroB7Sz7e7SpfZaNVfNypScNxlXrpnqwmjgx7X7xbDu/8Lu34j3I4QHERggO6DV9heBmu9uGyrk54PbxwtxyrkVwj4ov+21ywb/L2HFBHVn0EjBaF3Jo=
    distributions: sdist bdist_wheel
    on:
      tags: true
      branch: master
